config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#index'  
  # root to: "devise/registrations#new"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show]
  resources :posts
  resources :comments#, only: [:create, :show]
  resources :likes

  post '/cancelfriend', to: 'friendships#cancel', as: 'cancelfriend'
  post '/acceptfriend', to: 'friendships#create'
  post '/deletefriend', to: 'friendships#destroy'
  resources :friendships, only: [:index, :show, :update]
  get 'friends', to: 'users#friends'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_bootstrap.html.erb
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

app/views/layouts/_default.html.erb
 
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

app/views/layouts/_flash_msg.html.erb
<% flash.each do |msg_type, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{msg_type}")%>
<% end %>
<%# <p class="notice"><%= notice</p> %>
<%# <p class="alert"><%= alert</p> %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-expand-md navbar-light bg-primary">
  <div class="container">
    <i class="fa fa-facebook-square fa-2x mt-1 mr-2 fa-bg-white fb"></i>
    <%= link_to "Friendbook", root_path, class: "text-white pr-2" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
      <div class="collapse navbar-collapse float-right" id="navbarNavDropdown">
        <ul class="nav navbar-nav justify-content-end">
          <% if signed_in? %>
            <li class="nav-item text-white"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'text-danger pr-4' %></li>
            <a href="">
            <%#= image_tag('default_avatar.png', class: "img-fluid profile-avatar img-pro-size") %>
            <span><%= link_to "#{current_user.first_name}", posts_path, class: 'text-white pl-2' %></span>
            <li class="nav-item text-white">
              <span><%= link_to "Friends (#{all_friends})", friends_path, class: 'text-white pl-2' %></span>
            </li>
            <li class="nav-item text-white">
              <span><%= link_to "Friend requests (#{unconfirmed_requests.size})", friendships_path, class: 'text-white pl-2' %></span>
            </li>
            </a>
          <% else %>  
            <li class="nav-item"><%= link_to 'Log in', user_session_path, class: 'text-white pr-2' %></li>
            <li class="nav-item"><%= link_to 'Sign up', new_user_registration_path, class: 'text-white pr-2' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= render 'layouts/bootstrap'%>
    <%= render 'layouts/default'%>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <%= render 'layouts/flash_msg'%>
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
    <%# <div class="well"> %>
      <%#= debug(params) if Rails.env.development? %>
    <%# </div> %>
  </body>
</html>